"""init

Revision ID: 48d5f3a4582f
Revises: 
Create Date: 2026-05-12 00:59:04.849444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d5f3a4582f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('firebase_uid', sa.String(length=255), nullable=False),
    sa.Column('residence_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_Users_firebase_uid'), 'Users', ['firebase_uid'], unique=True)
    op.create_table('community_categories',
    sa.Column('community_category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=30), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('community_category_id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('disaster_types',
    sa.Column('disaster_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disaster_code', sa.String(length=30), nullable=False),
    sa.Column('disaster_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('disaster_type_id'),
    sa.UniqueConstraint('disaster_code')
    )
    op.create_table('recovery_stage_masters',
    sa.Column('recovery_stage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage_code', sa.String(length=30), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('recovery_stage_id'),
    sa.UniqueConstraint('stage_code')
    )
    op.create_table('community_profiles',
    sa.Column('community_profile_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('intro_message', sa.String(length=255), nullable=True),
    sa.Column('contribution_badge', sa.String(length=50), nullable=True),
    sa.Column('contribution_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_auth_provider',
    sa.Column('auth_provider_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.Enum('GOOGLE', 'EMAIL', 'FACEBOOK', name='providertype'), nullable=False),
    sa.Column('provider_uid', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auth_provider_id')
    )
    op.create_index(op.f('ix_user_auth_provider_user_id'), 'user_auth_provider', ['user_id'], unique=False)
    op.create_table('user_disasters',
    sa.Column('user__disaster_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disaster_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('registration_status', sa.Enum('ACTIVE', 'EXPIRED', 'ARCHIVED', name='registrationstatus'), nullable=False),
    sa.Column('recovery_stage_id', sa.Integer(), nullable=False),
    sa.Column('recovery_progress', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disaster_type_id'], ['disaster_types.disaster_type_id'], ),
    sa.ForeignKeyConstraint(['recovery_stage_id'], ['recovery_stage_masters.recovery_stage_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user__disaster_id')
    )
    op.create_index(op.f('ix_user_disasters_user_id'), 'user_disasters', ['user_id'], unique=False)
    op.create_table('user_residences',
    sa.Column('residence_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_name', sa.String(length=200), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', name='verificationstatus'), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('residence_id')
    )
    op.create_index(op.f('ix_user_residences_user_id'), 'user_residences', ['user_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('checklist_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user__disaster_id', sa.Integer(), nullable=False),
    sa.Column('checklist_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('item_source_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user__disaster_id'], ['user_disasters.user__disaster_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checklist_item_id')
    )
    op.create_index(op.f('ix_checklist_items_checklist_date'), 'checklist_items', ['checklist_date'], unique=False)
    op.create_index(op.f('ix_checklist_items_user__disaster_id'), 'checklist_items', ['user__disaster_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('community_posts_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user__disaster_id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('community_category_id', sa.BigInteger(), nullable=False),
    sa.Column('post_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('empathy_count', sa.Integer(), nullable=False),
    sa.Column('scrap_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_category_id'], ['community_categories.community_category_id'], ),
    sa.ForeignKeyConstraint(['residence_id'], ['user_residences.residence_id'], ),
    sa.ForeignKeyConstraint(['user__disaster_id'], ['user_disasters.user__disaster_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('community_posts_id')
    )
    op.create_index(op.f('ix_community_posts_post_type'), 'community_posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_community_posts_user_id'), 'community_posts', ['user_id'], unique=False)
    op.create_table('daily_status_checks',
    sa.Column('daily_check_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user__disaster_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('emotion_score', sa.Integer(), nullable=False),
    sa.Column('condition_score', sa.Integer(), nullable=False),
    sa.Column('action_score', sa.Float(), nullable=False),
    sa.Column('change_score', sa.Integer(), nullable=False),
    sa.Column('need_score', sa.Float(), nullable=False),
    sa.Column('available_time', sa.Integer(), nullable=False),
    sa.Column('can_go_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user__disaster_id'], ['user_disasters.user__disaster_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daily_check_id')
    )
    op.create_index(op.f('ix_daily_status_checks_user__disaster_id'), 'daily_status_checks', ['user__disaster_id'], unique=False)
    op.create_table('disaster_impacts',
    sa.Column('impact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user__disaster_id', sa.Integer(), nullable=False),
    sa.Column('safety_status', sa.Enum('SAFE', 'MINOR', 'DAMAGED', 'EMERGENCY', name='safetystatus'), nullable=True),
    sa.Column('residence_status', sa.Enum('LIVABLE', 'PARTIAL_DAMAGE', 'UNLIVABLE', name='residencestatus'), nullable=False),
    sa.Column('injury_level', sa.Enum('NONE', 'MINOR', 'SEVERE', name='injurylevel'), nullable=False),
    sa.Column('can_go_out', sa.Boolean(), nullable=True),
    sa.Column('available_time', sa.Enum('UNDER_ONE_HOUR', 'ONE_TO_THREE_HOURS', 'ALL_DAY_HALF_DAY', name='availabletime'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user__disaster_id'], ['user_disasters.user__disaster_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('impact_id'),
    sa.UniqueConstraint('user__disaster_id')
    )
    op.create_table('recovery_features',
    sa.Column('feature_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user__disaster_id', sa.Integer(), nullable=False),
    sa.Column('feature_date', sa.Date(), nullable=False),
    sa.Column('onboarding_risk_level', sa.Integer(), nullable=False),
    sa.Column('avg_7d_status_score', sa.Float(), nullable=False),
    sa.Column('avg_7d_action_score', sa.Float(), nullable=False),
    sa.Column('outing_capability', sa.Float(), nullable=False),
    sa.Column('avg_7d_task_completion_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user__disaster_id'], ['user_disasters.user__disaster_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feature_id')
    )
    op.create_index(op.f('ix_recovery_features_user__disaster_id'), 'recovery_features', ['user__disaster_id'], unique=False)
    op.create_table('recovery_outputs',
    sa.Column('output_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user__disaster_id', sa.Integer(), nullable=False),
    sa.Column('recovery_stage_id', sa.Integer(), nullable=False),
    sa.Column('state_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_stage_id'], ['recovery_stage_masters.recovery_stage_id'], ),
    sa.ForeignKeyConstraint(['user__disaster_id'], ['user_disasters.user__disaster_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_index(op.f('ix_recovery_outputs_user__disaster_id'), 'recovery_outputs', ['user__disaster_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allow_push_notification', sa.Boolean(), nullable=True),
    sa.Column('user__disaster_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user__disaster_id'], ['user_disasters.user__disaster_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_setting_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('archive_items',
    sa.Column('archive_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_setting_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.BigInteger(), nullable=False),
    sa.Column('archive_date', sa.Date(), nullable=False),
    sa.Column('archive_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.checklist_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_setting_id'], ['user_settings.user_setting_id'], ),
    sa.PrimaryKeyConstraint('archive_item_id')
    )
    op.create_index(op.f('ix_archive_items_checklist_item_id'), 'archive_items', ['checklist_item_id'], unique=False)
    op.create_table('community_post_links',
    sa.Column('community_post_link_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('community_posts_id', sa.BigInteger(), nullable=False),
    sa.Column('link_url', sa.String(length=1000), nullable=False),
    sa.Column('link_title', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_posts_id'], ['community_posts.community_posts_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_post_link_id')
    )
    op.create_table('community_posts_attachments',
    sa.Column('community_post_attachment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('community_posts_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_posts_id'], ['community_posts.community_posts_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_post_attachment_id')
    )
    op.create_table('earthquake_impacts',
    sa.Column('earth_impact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aftershock_feeling', sa.Enum('NONE', 'OCCASIONAL', 'CONTINUOUS', name='aftershockfeeling'), nullable=False),
    sa.Column('building_crack', sa.Boolean(), nullable=False),
    sa.Column('house_damage', sa.Boolean(), nullable=False),
    sa.Column('vehicle_damage', sa.Boolean(), nullable=False),
    sa.Column('electric_problem', sa.Boolean(), nullable=False),
    sa.Column('water_problem', sa.Boolean(), nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impact_id'], ['disaster_impacts.impact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('earth_impact_id'),
    sa.UniqueConstraint('impact_id')
    )
    op.create_table('fire_impacts',
    sa.Column('fire_impact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fire_damage_scope', sa.Enum('SMOKE_ONLY', 'PARTIAL_LOSS', 'TOTAL_LOSS', name='firedamagescope'), nullable=False),
    sa.Column('smoke_inhalation', sa.Enum('NONE', 'MILD', 'SEVERE', name='smokeinhalation'), nullable=False),
    sa.Column('house_damage', sa.Boolean(), nullable=False),
    sa.Column('soot_damage', sa.Boolean(), nullable=False),
    sa.Column('debris_exist', sa.Boolean(), nullable=False),
    sa.Column('vehicle_damage', sa.Boolean(), nullable=False),
    sa.Column('electric_problem', sa.Boolean(), nullable=False),
    sa.Column('water_problem', sa.Boolean(), nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impact_id'], ['disaster_impacts.impact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fire_impact_id'),
    sa.UniqueConstraint('impact_id')
    )
    op.create_table('flood_impacts',
    sa.Column('flood_impact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flood_level', sa.Enum('NONE', 'FRONT_YARD', 'FIRST_FLOOR', 'INSIDE_HOME', name='floodlevel'), nullable=False),
    sa.Column('water_drain_status', sa.Enum('STILL_PRESENT', 'PARTIAL_DRAINED', 'MOSTLY_DRAINED', name='waterdrainstatus'), nullable=False),
    sa.Column('damage_house', sa.Boolean(), nullable=False),
    sa.Column('damage_vehicle', sa.Boolean(), nullable=False),
    sa.Column('electric_problem', sa.Boolean(), nullable=False),
    sa.Column('water_problem', sa.Boolean(), nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impact_id'], ['disaster_impacts.impact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flood_impact_id'),
    sa.UniqueConstraint('impact_id')
    )
    op.create_table('typhoon_impacts',
    sa.Column('typhoon_impact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('roof_damage', sa.Boolean(), nullable=False),
    sa.Column('window_damage', sa.Boolean(), nullable=False),
    sa.Column('structure_damage', sa.Boolean(), nullable=False),
    sa.Column('vehicle_damage', sa.Boolean(), nullable=False),
    sa.Column('electric_problem', sa.Boolean(), nullable=False),
    sa.Column('water_problem', sa.Boolean(), nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impact_id'], ['disaster_impacts.impact_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('typhoon_impact_id'),
    sa.UniqueConstraint('impact_id')
    )
    op.create_table('archive_files',
    sa.Column('archive_file_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('archive_item_id', sa.BigInteger(), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archive_item_id'], ['archive_items.archive_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('archive_file_id')
    )
    op.create_index(op.f('ix_archive_files_archive_item_id'), 'archive_files', ['archive_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archive_files_archive_item_id'), table_name='archive_files')
    op.drop_table('archive_files')
    op.drop_table('typhoon_impacts')
    op.drop_table('flood_impacts')
    op.drop_table('fire_impacts')
    op.drop_table('earthquake_impacts')
    op.drop_table('community_posts_attachments')
    op.drop_table('community_post_links')
    op.drop_index(op.f('ix_archive_items_checklist_item_id'), table_name='archive_items')
    op.drop_table('archive_items')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_recovery_outputs_user__disaster_id'), table_name='recovery_outputs')
    op.drop_table('recovery_outputs')
    op.drop_index(op.f('ix_recovery_features_user__disaster_id'), table_name='recovery_features')
    op.drop_table('recovery_features')
    op.drop_table('disaster_impacts')
    op.drop_index(op.f('ix_daily_status_checks_user__disaster_id'), table_name='daily_status_checks')
    op.drop_table('daily_status_checks')
    op.drop_index(op.f('ix_community_posts_user_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_post_type'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_checklist_items_user__disaster_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_checklist_date'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_user_residences_user_id'), table_name='user_residences')
    op.drop_table('user_residences')
    op.drop_index(op.f('ix_user_disasters_user_id'), table_name='user_disasters')
    op.drop_table('user_disasters')
    op.drop_index(op.f('ix_user_auth_provider_user_id'), table_name='user_auth_provider')
    op.drop_table('user_auth_provider')
    op.drop_table('community_profiles')
    op.drop_table('recovery_stage_masters')
    op.drop_table('disaster_types')
    op.drop_table('community_categories')
    op.drop_index(op.f('ix_Users_firebase_uid'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
